# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartfridgeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge_Day_Calories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='fridge',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='fridge_day_calories',
            name='fridge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfridgeapp.Fridge'),
        ),
    ]
