# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfridgeapp', '0003_auto_20170305_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge_day_calories',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
