# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfridgeapp', '0004_auto_20170305_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_fridge',
            name='threshold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
