# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartfridgeapp', '0005_auto_20170305_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('basket_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Basket_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfridgeapp.Basket')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfridgeapp.Item')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='items',
            field=models.ManyToManyField(through='smartfridgeapp.Basket_Item', to='smartfridgeapp.Item'),
        ),
        migrations.AddField(
            model_name='basket',
            name='shopper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
