# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfridgeapp', '0009_auto_20170305_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
        migrations.AddField(
            model_name='basket_item',
            name='unit',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
