# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfridgeapp', '0010_auto_20170305_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_store',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='item_store',
            old_name='store_id',
            new_name='store',
        ),
        migrations.AlterField(
            model_name='item_store',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
